#!/bin/bash
# Auto-revert turnaround timelines in help.html back to pre-high-demand values.
# Scheduled to run 2026-04-08 — generated by Claude Code on 2026-03-25.

FILE="/Users/billyjoinville/GitHub/webeaze/help.html"

sed -i '' "s/updated: '03-25-2026'/updated: '01-19-2026'/" "$FILE"
sed -i '' 's|<tr><td>Text or image edits</td><td>1 to 2 weeks</td></tr>|<tr><td>Text or image edits</td><td>1 to 3 days</td></tr>|' "$FILE"
sed -i '' 's|<tr><td>Additional pages</td><td>2 weeks</td></tr>|<tr><td>Additional pages</td><td>5 to 7 days</td></tr>|' "$FILE"
sed -i '' 's|<tr><td>Mobile optimization fixes</td><td>1 to 2 weeks</td></tr>|<tr><td>Mobile optimization fixes</td><td>1 to 3 days</td></tr>|' "$FILE"
sed -i '' 's|<tr><td>SEO updates</td><td>1 to 2 weeks</td></tr>|<tr><td>SEO updates</td><td>1 to 3 days</td></tr>|' "$FILE"
sed -i '' 's|<tr><td>Contact form edits</td><td>1 to 2 weeks</td></tr>|<tr><td>Contact form edits</td><td>1 to 3 days</td></tr>|' "$FILE"
sed -i '' 's|<tr><td>Full website audit or revamp</td><td>3 to 4 weeks</td></tr>|<tr><td>Full website audit or revamp</td><td>7 to 14 business days</td></tr>|' "$FILE"
sed -i '' 's|<tr><td>Bug fixes or site issues</td><td>3 to 5 days\*</td></tr>|<tr><td>Bug fixes or site issues</td><td>24 to 48 hours*</td></tr>|' "$FILE"

# Self-delete this script and remove crontab entry after running
crontab -l | grep -v '.revert-turnarounds.sh' | crontab -
rm -- "$0"
